### ISSUE TITLE
'GRUTree' object has no attribute 'fit_tree'

### ISSUE THREAD

**Issue by mitakas** [dtak/tree-regularization-public#1]
Hi, I tried running 

```
python train.py --strength 1000.0
```

but I get the following exception after the 12th retrain:

```
Traceback (most recent call last):
  File "train.py", line 312, in <module>
    batch_size=10, lr=1e-2, param_scale=0.1, log_every=10)
  File "train.py", line 62, in train
    self.tree = self.fit_tree(self.weights, X_train, F_train, y_train)
AttributeError: 'GRUTree' object has no attribute 'fit_tree'
```

It seems that 

```
self.tree = self.fit_tree(self.weights, X_train, F_train, y_train)
```

on [line 62 in train.py](https://github.com/dtak/tree-regularization-public/blob/master/train.py#L62)

should be

```
self.tree = self.gru.fit_tree(self.weights, X_train, F_train, y_train)
```

Here is the [tree.pdf](https://github.com/dtak/tree-regularization-public/files/1603071/tree.pdf) that gets generated.

**Comment by mhw32** [comment]
Great catch! I added your fix here: https://github.com/dtak/tree-regularization-public/commit/05a7cfaec0cef74f63b1ccc798b9da60b407d252
 
Closing the issue for now. If there are more problems, feel free to re-open it.
Thanks for contributing!
